### PR TITLE
Sanitize files names - fix #54 and #79

### LINKED ISSUE #54: [Win10] Documentation Name: Solved!
Hey, guys! After hours struggling with roam-to-git and win10, and I finally found a work around (isn't a beautiful solution, but is a effective one). So, Who is this for?

0) Using Windows 10
1) When debugging everything should work flawless: roam-to-git open chrome and downloads your files, put doesn't unzip
2) When using the normal command (roam-to-git notes/) getting some error like: can't create path for "the_name_of_your_note?"

The problem is: when we are using roam research, we just put symbols like: "; ? and |. But when unzipping to send to git, the files need to be saved in windows, and this piece of shit can't create files with names like: 'What's the capital of France?.md.', because it reserve [characters] Therefore, roam-to-git can't do its magic. 

---
## **Solution**
Just substitute the _reserved characters_ to others. Problem: if you have a lot of files in roam research this will be a huge pain (Probably there's some smart way to do it. I went to brute force). My suggestions:

? ⇒ ？(full width)
: ⇒ - (hyphen)
| ⇒ - (hyphen)
" ⇒ ' (simple quote)

I thing these are the most frequent. If you need to use other characters, you can search for alternatives on the character map app (win10 native).

---
Appendix: 
The following reserved characters:

< (less than)
'>' (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
'*' (asterisk)

### PR DESCRIPTION
**Pull request by MatthieuBizien**
fix #54 and #79

### CODE REVIEW

**Comment by RoamHenry** [comment]
Thank you Matthieu! So should it be working for me now? Still seeing my actions all fail

**Comment by MatthieuBizien** [comment]
@RoamHenry I think this PR should fix the bug, but I can't test your setup, as I don't have access to your Roam.

The page name you had an issue with [work](https://github.com/MatthieuBizien/roam-to-git-demo/blob/master/formatted/Like%20optical%20illusions%2C%20intellectual%20illusions%20can%20trick%20us%20into%20thinking%20something%20that%20isn't%20actually%20there%20or%20true.%20As%20with%20optical%20illusions%2C%20even%20when%20we%20know%20they%20are%20there%20we%20still%20have%20to%20actively%20override%20our%20default%20perception%20to%20get%20to%20the%20trut) when I had it into the [demo Roam of roam-to-git](https://roamresearch.com/#/app/roam-to-git-demo/page/-J6HZkWg2)

If the problem is still the same, could you re-open #79 and add the new (detailed) traceback?

If it's a different one, could you open a new issue, with a detailed traceback and the context?

**Comment by RoamHenry** [comment]
@MatthieuBizien Hurrah! It is working again!! Thank you for solving this issue and deeply grateful for the gift of your intellect (and code). Hard to express how much calm this backup brings to my world.

Thank you!!

**Comment by everruler12** [comment]
This can cause a collision issue. For example, create two pages:
[[/test]] then [[test]]

The backup will only have test.md
Any markdown references to [[/test]] will not be hyperlinked.

**Pull request merged**
